### ISSUE TITLE
titles_combined.txt file should be accessible from library

### ISSUE THREAD

**Issue by pritul98** [fluquid/find_job_titles#4]
**Using the API,**

1) some titles are in title case and some of the titles like .NET are in upper case so we can not change input case into any particular case.

2) If the file is accessible then we can add some new titles if we want.

Please you should add this if possible

**Comment by codinguncut** [comment]
I think I lower-cased everything, since titles can appears as "Vice President" or "vice president".
I think default indexer may be case-sensitive, but there is an alternate algo included that can do case-insensitive search.

File is accessible here:
https://github.com/fluquid/find_job_titles/blob/master/src/find_job_titles/data/titles_combined.txt.gz

But it would probably be a good idea to be able to override this as a library.

**Comment by pritul98** [comment]
**oh, thank you for replying.**
I figured it out in the library I changed the load_titles() method asked because I am new to python.
now just one thing that when I change the text inside the title file or pass a text file it gives me the error that got the string instead of bytes so, will have to do something about that.

**Comment by codinguncut** [comment]
If you paste your code re: `load_titles()` maybe I can help.
I assume you are using python 3, and the output from load_titles should be list of `str`, I think

**Comment by pritul98** [comment]
**yes python3, I am using your method only with changed file I am doing,**
def new_load_titles():
    with resource_stream('find_job_titles',
                         'data/titles_combined.txt.gz') as fhandle:
        with gzip.GzipFile(fileobj=fhandle, mode='r') as gzf:
            for line in gzf:
                # Note: decode rather than "rt" for py2 compat
                # TODO: using pyahocorasick this should now be 'str' again ;(
                yield line.decode('utf-8').strip().**lower()**)

from find_job_titles import load_titles
load_titles= new_load_titles()

I am changing the content inside the file and converting them to lower case in this method

**Comment by pritul98** [comment]
**Solved It by reading the text file as bytes and reading it with open**

```
def fload_titles():
    """
    load job titles as generator from txt.gz file included in the library
    """
    with open("data/titles_combined.txt", "rb") as input:
        for line in input:
                yield line.decode('utf-8').strip().lower()
```
